wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/144141829_p0.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/144141829_p0.jpg
    fit_mode = cover
}
